services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    
    environment:
      - "DEBUG=0"
      - "SECRET_KEY=*2t$t!p-pa38rnvk7^dec+ki%66vpxtyw#0tzk6xy(n6$b%3@a"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

    volumes:
      - ".:/code"

    ports:
      - "8000:8000"

    depends_on:
      - db
  db:
    image: postgres:13

    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
